Parameters:
 VpcParameter:
  Description: Enter CIDR for VPC
  Type: String
  Default: 10.0.0.0/20
  AllowedValues:
   - 10.0.0.0/16
   - 10.0.0.0/20
   - 192.168.0.0/16
   - 192.168.0.0/20
 PublicSubnet1Parameter:
  Description: Enter CIDR for Public Subnet 1 Ex - 10.0.1.0/24
  Type: String
 PublicSubnet2Parameter:
  Description: Enter CIDR for Public Subnet 2 Ex - 10.0.2.0/24
  Type: String
  
Resources:
 WebAppVpc:
  Type: AWS::EC2::VPC
  Properties:
   CidrBlock: !Ref VpcParameter
   Tags:
   - Key: Name
     Value: Application Vpc

 InternetGateway:
  Type: AWS::EC2::InternetGateway
  Properties:
   Tags:
   - Key: Name
     Value: Internet Gateway
 InternetGatewayAttachment:
  Type: AWS::EC2::VPCGatewayAttachment
  Properties:
   InternetGatewayId: !Ref InternetGateway
   VpcId: !Ref WebAppVpc

 Subnet1:
  Type: AWS::EC2::Subnet
  Properties:
   CidrBlock: !Ref PublicSubnet1Parameter
   MapPublicIpOnLaunch: true
   VpcId: !Ref WebAppVpc
   Tags:
   - Key: Name
     Value: Public Subnet 1
 Subnet2:
  Type: AWS::EC2::Subnet
  Properties:
   CidrBlock: !Ref PublicSubnet2Parameter
   MapPublicIpOnLaunch: true
   VpcId: !Ref WebAppVpc
   Tags:
   - Key: Name
     Value: Public Subnet 2

 RouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
   VpcId: !Ref WebAppVpc
   Tags:
   - Key: Name
     Value: Route Table
 RouteTableRoutes:
  Type: AWS::EC2::Route
  Properties: 
   DestinationCidrBlock: 0.0.0.0/0
   GatewayId: !Ref InternetGateway
   RouteTableId: !Ref RouteTable
 Subnet1RouteTableSubnetAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
   RouteTableId: !Ref RouteTable
   SubnetId:
    Ref: Subnet1
 Subnet2RouteTableSubnetAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
   RouteTableId: !Ref RouteTable
   SubnetId: 
    Ref: Subnet2
   
 NetworkAcl:
  Type: AWS::EC2::NetworkAcl
  Properties:
   VpcId: !Ref WebAppVpc
   Tags:
   - Key: Name
     Value: NetworkAcl
 NetworkAclEntryIngressEphemeral:
  Type: AWS::EC2::NetworkAclEntry
  Properties:
   CidrBlock: 0.0.0.0/0
   Egress: false
   NetworkAclId: !Ref NetworkAcl
   Protocol: 6
   PortRange:
    From: 32768
    To: 65535
   RuleAction: allow
   RuleNumber: 100
 NetworkAclEntryEgressEphemeral:
  Type: AWS::EC2::NetworkAclEntry
  Properties:
   CidrBlock: 0.0.0.0/0
   Egress: true
   NetworkAclId: !Ref NetworkAcl
   Protocol: 6
   PortRange:
    From: 32768
    To: 65535
   RuleAction: allow
   RuleNumber: 100
 NetworkAclEntryIngressHTTP:
  Type: AWS::EC2::NetworkAclEntry
  Properties:
   CidrBlock: 0.0.0.0/0
   Egress: false
   NetworkAclId: !Ref NetworkAcl
   Protocol: 6
   PortRange:
    From: 80
    To: 80
   RuleAction: allow
   RuleNumber: 101
 NetworkAclEntryEgressHTTP:
  Type: AWS::EC2::NetworkAclEntry
  Properties:
   CidrBlock: 0.0.0.0/0
   Egress: true
   NetworkAclId: !Ref NetworkAcl
   Protocol: 6
   PortRange:
    From: 80
    To: 80
   RuleAction: allow
   RuleNumber: 102
 NetworkAclEntryIngressHTTPS:
  Type: AWS::EC2::NetworkAclEntry
  Properties:
   CidrBlock: 0.0.0.0/0
   Egress: false
   NetworkAclId: !Ref NetworkAcl
   Protocol: 6
   PortRange: 
    From: 443
    To: 443
   RuleAction: allow
   RuleNumber: 103
 NetworkAclEntryEgressHTTPS:
  Type: AWS::EC2::NetworkAclEntry
  Properties:
   CidrBlock: 0.0.0.0/0
   Egress: true
   NetworkAclId: !Ref NetworkAcl
   Protocol: 6
   PortRange:
    From: 443
    To: 443
   RuleAction: allow
   RuleNumber: 103

 Subnet1NetworkAclSubnetAssociations:
  Type: AWS::EC2::SubnetNetworkAclAssociation
  Properties:
   SubnetId:
    Ref: Subnet1
   NetworkAclId: !Ref NetworkAcl
 Subnet2NetworkAclSubnetAssociations:
  Type: AWS::EC2::SubnetNetworkAclAssociation
  Properties:
   SubnetId: 
    Ref: Subnet2
   NetworkAclId: !Ref NetworkAcl
 
Outputs:
 VpcOutput:
  Description: Output of VPC ID
  Value: !Ref WebAppVpc
  Export:
   Name: !Sub "Vpc-Id"
 PublicSubnet1Output:
  Description: Output of PublicSubnet1 Id
  Value: !Ref Subnet1
  Export:
   Name: !Sub "Subnet1-Id"
 PublicSubnet2Output:
  Description: Output of PublicSubnet2 Id
  Value: !Ref Subnet2
  Export:
   Name: !Sub "Subnet2-Id"